### ISSUE TITLE
I have to install tf before running the script?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [caogang/wgan-gp#7]
It seems that it depends on some tf funcitons . Can it totally be implemented by pytorch? If not, why?
Also, the code isn't compatible with python3.

**Comment by caogang** [comment]
Oh, it's my fault. I haven't clean the code of gan_language.py. The new version has been commited.

Since I have only used some plot and dataset functions in tflib, not using any ops of tf. So I borrow the code. However, there is no need to install tf, the implementation is totally by pytorch.

Thank you for your feedback.

**Comment by Naruto-Sasuke** [comment]
Thank you.
